### PR TITLE
Tests fixing and refactoring

### LINKED ISSUE #123: AttrBase.kt:43: AttrBase test needs to be refactored....
The puzzle `121-c98915f6` from #121 has to be resolved: 

https://github.com/objectionary/ddr/blob/16fcf13fb05c1e0270931e64c97ff8067c74a0ff/src/test/kotlin/org/objectionary/ddr/unit/graph/attr/AttrBase.kt#L43-L43

The puzzle was created by @c71n93 on 13-Jul-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by c71n93**
Closes #123, #124, #125, #126, #127. 

Simplified tests logic. This PR is needed for the following fixes.

---

## PR-Codex overview
This PR focuses on refactoring and organizing test classes in the codebase. 

### Detailed summary:
- Deleted `IntegrationDdrWorkflowBase.ktsrc/test/kotlin/org/objectionary/ddr/integration/IntegrationDdrWorkflowBase.ktsrc/test/kotlin/org/objectionary/ddr/TestNotFoundException.kt`.
- Added `TestNotFoundException.kt` class.
- Added `UnitTestBase.kt` interface.
- Renamed `IntegrationDdrWorkflowTest.kt` to `DdrWorkflowTest.kt` and moved it to `workflow` package.
- Added `IntegrationTestBase.kt` interface.
- Added `constructResultPath` function to `IntegrationTestBase.kt`.
- Updated imports and implemented `UnitTestBase` in `TempDirectoryBase.kt`.
- Updated `TestBase.kt` interface with new properties and functions.
- Updated `Sources.kt` class with new private properties and updated function names.
- Updated `DdrWorkflowBase.kt` with new imports and updated function names.
- Updated `AttrBase.kt` with new imports and updated function names.

> The following files were skipped due to too many changes: `src/test/kotlin/org/objectionary/ddr/unit/graph/attr/AttrBase.kt`, `src/test/kotlin/org/objectionary/ddr/unit/graph/inner/InnerBase.kt`, `src/test/kotlin/org/objectionary/ddr/unit/graph/builder/BuilderBase.kt`, `src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by c71n93** [comment]
@Graur please review

**Comment by c71n93** [comment]
@Graur could you review this, please?

File: src/main/kotlin/org/objectionary/ddr/sources/Sources.kt [hunk 1]
```diff
@@ -80,6 +82,9 @@ class SrsTransformed(
      *
      * @param filename path to current xmir file in source directory
      * @return path to the temporary directory with xmir files
+     *
+     * @todo #121:30min if output directory already exists createFile throws exception and logger prints error message. This situation should be handled correctly.
+     * @todo #121:30min rename "tmpPath" to "resPath" and make it a public field.
```
Comment (Graur) [inline src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:87]: @c71n93 Is it worth creating such an issue? Looks like a refactoring that can be done in this pull request

File: src/test/kotlin/org/objectionary/ddr/TestBase.kt [hunk 2]
```diff
@@ -74,7 +84,29 @@ interface TestBase {
...
-        .substring(5)
-        .replace(' ', '_')
+    fun getTestName(): String? {
+        Thread.currentThread().stackTrace.forEach {
+            val methodName = it.methodName
+            if (methodName.substring(0, "test ".length) == "test ") {
+                return methodName.substring("test ".length).replace(' ', '_')
+            }
+        }
+        return null
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/TestBase.kt:94]: @c71n93 Maybe it would be better to throw an exception here? According to: https://www.yegor256.com/2014/05/13/why-null-is-bad.html

File: src/test/kotlin/org/objectionary/ddr/TestBase.kt [hunk 3]
```diff
@@ -74,7 +84,29 @@ interface TestBase {
...
+     *
+     * @param pathToSource path to source directory
+     * @throws IOException
+     */
+    fun deleteTempDir(pathToSource: Path) {
+        val tmpDir = File("${pathToSource}_$postfix")
+        try {
+            FileUtils.deleteDirectory(tmpDir)
+        } catch (e: IOException) {
+            logger.error(e.message)
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/TestBase.kt:108]: @c71n93 Maybe it would be better to re-throwing an exception like here: https://github.com/objectionary/ddr/pull/128/files

**Review by Graur — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/objectionary/ddr/sources/Sources.kt (hunk 1 above)
Comment (c71n93) [reply src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:87]: @Graur There are more changes than I expected. I think, this issue can be resolved together with others issues for this class (there are 3 of them). When I was making these todos, I was going to solve them in the next one PR. What do you think?

Comment (Graur) [reply src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:87]: @c71n93 Sure, let's keep this `todo`

File: src/main/kotlin/org/objectionary/ddr/sources/Sources.kt [hunk 4]
```diff
@@ -37,26 +37,26 @@ class SrsTransformed(
 ) : Sources {
     private val logger = LoggerFactory.getLogger(this.javaClass.name)
 
-    /** @property path path to directory with source files or single source file */
-    val path: Path = Path.of(strPath)
+    /** @property inPath path to directory with source files or single source file */
+    val inPath: Path = Path.of(strPath)
```
Comment (Graur) [inline src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:41]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: src/main/kotlin/org/objectionary/ddr/sources/Sources.kt [hunk 5]
```diff
@@ -99,9 +102,10 @@ class SrsTransformed(
      *
      * @param filename path to current xmir file in source directory
      * @return path to the temporary directories
+     *
      */
     private fun generateTmpPath(filename: String): String {
-        val strPath = path.toString()
+        val strPath = inPath.toString()
```
Comment (Graur) [inline src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:108]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: src/test/kotlin/org/objectionary/ddr/TestBase.kt [hunk 6]
```diff
@@ -73,8 +83,30 @@ interface TestBase {
 
     /**
      * @return name of the test being executed
+     * @throws TestNotFoundException
+     */
+    fun getTestName(): String {
+        Thread.currentThread().stackTrace.forEach {
+            val methodName = it.methodName
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/TestBase.kt:90]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: src/test/kotlin/org/objectionary/ddr/TestBase.kt [hunk 7]
```diff
@@ -73,8 +83,30 @@ interface TestBase {
...
+     * Deletes temporary output directory
+     *
+     * @param pathToSource path to source directory
+     * @throws IOException
      */
-    fun getTestName() = Thread.currentThread().stackTrace[4].methodName
-        .substring(5)
-        .replace(' ', '_')
+    fun deleteTempDir(pathToSource: Path) {
+        val tmpDir = File("${pathToSource}_$postfix")
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/TestBase.kt:105]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt [hunk 8]
```diff
@@ -43,78 +43,53 @@ import org.cactoos.io.ResourceOf
...
             .forEach { file ->
-                val actualBr: BufferedReader = File(file.toString()).bufferedReader()
-                val actual = actualBr.use { it.readText() }
-                val expectedFile = cmpFiles.find {
-                    it.substringAfterLast(path) == file.toString().substringAfterLast(path)
-                }
-                val expectedBr: BufferedReader = File(expectedFile.toString()).bufferedReader()
-                val expected = expectedBr.use { it.readText() }
+                val expected = File(file.toString()).bufferedReader().use { it.readText().replace(" ", "") }
+                val actualFilename = file.toString().replace("$eoOutTmp$sep", "out$sep")
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt:78]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt [hunk 9]
```diff
@@ -145,18 +132,27 @@ open class ResolverBase : TestBase {
         return XSLDocument(stripXml).with(ClasspathSources()).transform(xmir)
     }
 
+    override fun deleteTempDir(pathToSource: Path) {
+        val tmpDir = File("${pathToSource}_$postfix")
```
Comment (Graur) [inline src/test/kotlin/org/objectionary/ddr/integration/resolver/ResolverBase.kt:136]: @c71n93 We are trying to avoid compound names. According to: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

**Review by Graur — CHANGES_REQUESTED** [review]
@c71n93 Good one! Just a few comments about compound names:

File: src/main/kotlin/org/objectionary/ddr/sources/Sources.kt (hunk 4 above)
Comment (c71n93) [reply src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:41]: @Graur I'm planning to add public field `resPath` with path to result directory in the next PR. Thus, compound naming is necessary to distinguish between input and result paths. I can name these fields `inputs` and `results` and in context of this class it will be fine. But these fields are public, so in another context it won't be clear that `sources.results` is the path to the results directory. What do you think?

Comment (Graur) [reply src/main/kotlin/org/objectionary/ddr/sources/Sources.kt:41]: @c71n93 Maybe just `input` and `path`? It is just a single path to directory, am I right?

**Comment by Graur** [comment]
@c71n93 What about your unverified commits? Did you sigh your commits by GPG keys?

**Comment by c71n93** [comment]
> @c71n93 What about your unverified commits? Did you sigh your commits by GPG keys?

@Graur Yeah, it looks like I had issue with my ssh key. I have fixed it.

**Review by Graur — APPROVED** [review]
@c71n93 Looks good to me, thanks!
@yegor256 Could you please have a look?

**Comment by c71n93** [comment]
@yegor256 could you please take a look?

**Comment by yegor256** [comment]
@rultor mertge
